FROM node:22-slim

WORKDIR /app

COPY package*.json ./
RUN npm ci --only=production

FROM node:22-slim
WORKDIR /app
COPY --from=builder /app/node_modules ./node_modules
COPY server/ ./server

EXPOSE 8080

CMD [ "node", "server/webrtc-server.js" ]